# -*- coding: utf-8 -*-
"""Homework_1_feedback

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u1UJDmmtKcZPSE3PYPEaeMQeuX7I9HIt

# Overall Score

You received 37 out of 45 points.

Before you turn this problem in, make sure everything runs as expected. First, **restart the kernel** (in the menubar, select Kernel$\rightarrow$Restart) and then **run all cells** (in the menubar, select Cell$\rightarrow$Run All).

Make sure you fill in any place that says `YOUR CODE HERE` or "YOUR ANSWER HERE", as well as your name and collaborators below:
"""

NAME = "Michael Xiong"
COLLABORATORS = ""

"""---

# CSE 30 Fall 2021 - Homework 1


### Instructions

Please disregard the YOUR NAME and COLLABORATORS above.  They are put there atomatically by the grading tool.
You can find instructions on how to work on a homework on Canvas.  Here is a short summary: 

### Submitting your work

To submit your work: 

* First, click on "Runtime > Restart and run all", and check that you get no errors.  This enables you to catch any error you might have introduced, and not noticed, due to your running cells out of order. 
* Second, download the notebook in .ipynb format (File > Download .ipynb) and upload the .ipynb file to [this form](https://docs.google.com/forms/d/e/1FAIpQLSdcFwJpyubrVG8aPA0f9g1TOzYWmkKIHCOXWqEgjl3PfdDptQ/viewform?usp=sf_link). 

You can submit multiple times; the last submission before the deadline is the one that counts.

### Homework format

For each question in this notebook, there is: 

* A text description of the problem. 
* One or more places where you have to insert your solution.  You need to complete every place marked: 

    `# YOUR CODE HERE`
    
    and you should not modify any other place. 
* One or more test cells.  Each cell is worth some number of points, marked at the top.  You should not modify these tests cells.  The tests pass if no error is printed out: when there is a statement that says, for instance: 

    `assert x == 2`
    
    then the test passes if `x` has value 2, and fails otherwise.  You can insert a `print(x)` (for this case!) somewhere if you want to debug your work; it is up to you.  
    
### Notes:

* Your code will be tested both according to the tests you can see (the `assert` statements you can see), _and_ additional tests.  This prevents you from hard-coding the answer to the particular questions posed.  Your code should solve the _general_ intended case, not hard-code the particular answer for the values used in the tests. 

* **Please do not delete or add cells!** The test is autograded, and if you modify the test by adding or deleting cells, even if you re-add cells you delete, you may not receive credit. 

* **Please do not import modules that are not part of the [standard library](https://docs.python.org/3/library/index.html).** You do not need any, and they will likely not available in the grading environment, leading your code to fail. 

* **If you are inactive too long, your notebook might get disconnected from the back-end.** Your work is never lost, but you have to re-run all the cells before you continue. 

* You can write out print statements in your code, to help you test/debug it. But remember: the code is graded on the basis of what it outputs or returns, not on the basis of what it prints.

* **TAs and tutors have access to this notebook,** so if you let them know you need their help, they can look at your work and give you advice. 

### Grading

Each cell where there are tests is worth a certain number of points.  You get the points allocated to a cell only if you pass _all_ the tests in the cell. 

The tests in a cell include both the tests you can see, and other, similar, tests that are used for grading only.  Therefore, you cannot hard-code the solutions: you really have to solve the essence of the problem, to receive the points in a cell. 

### Code of Conduct

* Work on the test yourself, alone. 
* You can search documentation on the web, on sites such as the Python documentation sites, Stackoverflow, and similar, and you can use the results. 
* You cannot share your work with others or solicit their help.

## Question 1: Encoding and Decoding Text

We will write simple functions to encode and decode text.  

### The decoding function

The decoding function takes as input a list of $n$ words $[w_0, w_1, \ldots, w_{n-1}]$, and a list of $m$ integers $[k_0, k_1, \ldots, k_{m-1}]$, where each integer is in the range $[0, \ldots, n-1]$. 

The function must output the string $w_{k_0} \; w_{k_1} \; w_{k_2} \; \ldots w_{k_m}$, where each number has been replaced with the word in the corresponding position in the list, and words are joined by spaces. 

For example, assume the function is called with: 

    textdecode(["a", "bird", "seed", "eats"], [0, 1, 3, 0, 2])
    
Then the output should be 

    "a bird eats a seed"
    
because word 0 in the list is "a", word 1 is "bird", word 3 is "eats", word 0 is "a", and word 2 is "seed". 

Here, we remind you that if you have a list of word, you can join them using spaces to form a string like this: 

    " ".join(["coffee", "is", "good"])
    
which produces

    "coffee is good"

You have to write the decode function.
"""

def textdecode(words, indices):
    """Decodes, producing a sentence in which each index is replaced
    by the word in the corresponding position in words, and the words
    are joined via spaces."""
    # YOUR CODE HERE
    new_str = ""
    for a in range(len(indices)):
      new_str +=  words[indices[a]] + " "
    return new_str[:len(new_str)-1]

# You can use this cell to test your code. 

# YOUR CODE HERE
assert textdecode(["be", "to", "not", "or"], [1, 0, 3, 2, 1, 0])

### For this question, you received 3 out of 3 points.

# 3 points: decoding function. 

assert textdecode(["a", "bird", "seed", "eats"], [0, 1, 3, 0, 2]) == "a bird eats a seed"
assert textdecode(["ha"], [0, 0, 0]) == "ha ha ha"
assert textdecode(["be", "to", "not", "or"], [1, 0, 3, 2, 1, 0]) == "to be or not to be"

### BEGIN HIDDEN TESTS
assert textdecode(["is", "this", "right", "wrong", "or"], [0, 1, 2, 4, 0, 1, 3]) == "is this right or is this wrong"
### END HIDDEN TESTS

"""### Encoding function

The encoding function works in the opposite way.  Given a sentence `s`, it first splits `s` according to spaces, via `s.split()`, obtaining a list of words.  It then removes duplicates from this list of words, and returns: 

* The list of words, with duplicates removed; 
* A list obtained by replacing each word with the index of the word in the above list. 

For instance, if the input is: 

    "i need a coffee"
    
then the words are `"i"`, `"need"`, `"a"`, `"coffee"`, and there are no duplicates.  The output will then be: 

    ["i", "need", "a", "coffee"], [0, 1, 2, 3]
    
If the [input is](https://www.youtube.com/watch?v=98luuj8ymoQ) 

    "yo ho ho and a bottle of rum"
    
the output can be 

    ["yo", "ho", "and", "a", "bottle", "of", "rum"], [0, 1, 1, 2, 3, 4, 5, 6]
    
or if you prefer, 

    ["a", "bottle", "of", "rum", "and", "yo", "ho"], [5, 6, 6, 4, 1, 2, 3]
    
which would decode to the same string.  
You have to write the encode function. 
"""

def textencode(s):
    """Encode the string s, dividing it into words, and returning a list 
    of unique words, and the list of indices of each word of s in the word list, 
    in order."""
    # YOUR CODE HERE

    new_str = list(set(s.split()))
    list_str = list(s.split())
    l1=[]
    for a in range(len(list_str)):
        for b in range(len(new_str)):
            if list_str[a]==new_str[b]:
                l1.append(b)
#    print(new_str, l1)
    return (new_str, l1)

# You can use this cell to test your code. 

# YOUR CODE HERE
assert textencode("c a a a a a")

### For this question, you received 4 out of 4 points.

# 4 point: simple tests

assert textencode("a") == (["a"], [0])
assert textencode("ho ho ho") == (["ho"], [0, 0, 0])

### For this question, you received 3 out of 3 points.

# 3 points: encoding / decoding tests

import random

words = ["a", "bi", "ci", "di", "e", "effe", "gi"]
for _ in range(1000):
    k = random.randint(0, 10)
    s = " ".join(random.choices(words, k=k))
    ws, ix = textencode(s)
    assert len(set(ws)) == len(set(ix))
    t = textdecode(ws, ix)
    assert s == t
    
### BEGIN HIDDEN TESTS
words = ["a", "bi", "ci", "di", "e", "effe", "gi"]
for _ in range(1000):
    k = random.randint(0, 20)
    s = " ".join(random.choices(words, k=k))
    ws, ix = textencode(s)
    assert len(ws) == len(set(s.split()))
    t = textdecode(ws, ix)
    assert s == t
### END HIDDEN TESTS

"""## Question 2: Numerical Dictionaries

This question considers _numerical dictionaries_, which map keys to integers (rather than to arbitrary values).  These dictionaries can be used to count occurrences; for instance, the dictionary {'a': 1, 'b': 3} indicates that 'a' occurred once, and 'b' three times. 

Write a function `add_dicts` that, given two numerical dictionaries, computes the numerical dictionary resulting from their sum.  For instance, `add_dict({'a': 1, 'b': 3}, {'b': 2, 'c': 3})` should give `{'a': 1, 'b': 5, 'c': 3}` as result.
"""

def add_dicts(d1, d2):
    # YOUR CODE HERE
    for s in d2:
      if s in d1:
        d1[s] = d1.get(s) + d2.get(s)
      else:
        d1[s] = d2[s]
#    print(d1)
    return d1

# You can use this cell to test your code. 

# YOUR CODE HERE
assert add_dicts({'x':5, 'y':1}, {'x':2, 'z':3})

### For this question, you received 4 out of 4 points.

# 4 points: When the keys are the same.

assert add_dicts({'a': 1, 'b': 2}, {'a': 3, 'b': 1}) == {'a': 4, 'b': 3}
# And empty.
assert add_dicts({}, {}) == {}

### BEGIN HIDDEN TESTS
assert add_dicts({'aa': 4, 'bb': 2}, {'aa': 3, 'bb': 8}) == {'aa': 7, 'bb': 10}
assert add_dicts({'aa': 4, 'bb': 2, 'cc': 5}, {'aa': 3, 'bb': 8, 'cc': 3}) == {'aa': 7, 'bb': 10, 'cc': 8}
### END HIDDEN TESTS

### For this question, you received 6 out of 6 points.

# 6 points: When the keys are different. 

assert add_dicts({'a': 1, 'c': 2}, {'a': 3, 'b': 1}), {'a': 4, 'b': 1, 'c': 2}
assert add_dicts({'a': 3, 'b': 1}, {'a': 1, 'c': 2}), {'a': 4, 'b': 1, 'c': 2}

### BEGIN HIDDEN TESTS
### END HIDDEN TESTS

"""## Question 3

Implement a function `ordered_substring` that takes as input two strings, s and t. 
The function returns True if and only if the characters of s can be found, in the order in which they are in s, as characters of t. In other words, the function returns True if and only if it is possible to remove some characters from t, so that the remaining ones  form the string s. 

For example:

* `ordered_substring("abc", "a123b4b523bc")` should return True, because `"a123b4b523bc"` contains the characters `"abc"` in that order, taking its 1st, 5th, and last character.
* Instead, `ordered_substring("abc", "a123c4b523b")` should return False, because `"a123c4b523b"` does not contain a "c" after a "b". 
* `ordered_substring("abb", "a123c4b523f")` should also return False, because there is no `"b"` after the first `"b"` in `"a123c4b523f"`. 

"""

def ordered_substring(s, t):
    """Returns True if s is an ordered substring of t, and False otherwise."""
    # YOUR CODE HERE
    if s == '':
#      print('T')
      return True
    elif t == '' or len(s) > len(t):
#      print('F')
      return False
    else:
      for a in range(len(s)):
        for b in range(len(t)):
          if s[a] not in t:
#            print('F')
            return False
          else:
            t = t[t.find(s[a]):]
            break
#      print('T')
      return True

# You can use this cell to test your code. 

# YOUR CODE HERE
ordered_substring('', 'abc')

### For this question, you received 2 out of 2 points.

# 2 points: Let us first test that the code works for empty and one-character strings s.

assert ordered_substring('', 'abc')
assert ordered_substring('a', 'cabd')
assert ordered_substring('d', 'cabd')
assert not ordered_substring('f', 'cabd')
assert not ordered_substring('a', '')
assert ordered_substring('', '')

### BEGIN HIDDEN TESTS
assert ordered_substring('2', '1234')
assert ordered_substring('1', '12345')
assert ordered_substring('5', '12345')
assert not ordered_substring('a', '12345')
### END HIDDEN TESTS

### For this question, you received 0 out of 2 points.

# 2 points: Some other simple cases.

assert ordered_substring('ab', 'abcd')
assert ordered_substring('ac', 'abcd')
assert ordered_substring('bd', 'abcd')
assert not ordered_substring('ba', 'abcd')
assert not ordered_substring('af', 'abcd')
assert ordered_substring('123', '12345')

### BEGIN HIDDEN TESTS
assert ordered_substring('12', '12345')
assert ordered_substring('15', '12345')
assert ordered_substring('45', '12345')
assert not ordered_substring('18', '12345')
assert not ordered_substring('32', '12345')
assert not ordered_substring('33', '12345')
### END HIDDEN TESTS

### For this question, you received 0 out of 6 points.

# 6 points: General cases.

assert ordered_substring('abc', 'abbbeec')
assert not ordered_substring('abbc', 'abc')
assert ordered_substring('aa', 'bacad')
assert ordered_substring('aaba', 'ababa')

### BEGIN HIDDEN TESTS
assert ordered_substring('13334', '12323434')
assert not ordered_substring('133344', '12323434')
assert not ordered_substring('333', '12323')
### END HIDDEN TESTS

"""## Question 4: Elections

Write an `Election` class, used to record votes.  The class has the following methods: 

* `vote(c)`: records a vote for candidate `c`. 
* `total_votes()`: returns the total number of votes. 
* `winner()`: returns the set of candidates with maximal votes.  Normally there is only one, but there could be a tie, in which case you return the set of tied candidates.  Return `None` if no votes have been cast.
* `margin()`: returns the margin of victory, that is, the number of votes separating the fist from the second candidate.  This can be 0, in case of a tie.  If there is only one candidate, you can answer with the number of votes for the candidate.  If no votes have been cast, return `None`. 

We provide the initializer method; the idea is to store the election status as a dictionary mapping candidate name to number of votes received.
"""

class Election(object):
    """Implements the election class."""

    def __init__(self):
        # Dictionary mapping voters to the number of votes received.
        self.votes = {}

    def vote(self, c):
        """Records a vote for candidate c."""
        # YOUR CODE HERE
        if c in self.votes:
          self.votes[c] += 1
        else:
          self.votes[c] = 1
    def total_votes(self):
        """Returns the total number of votes cast."""
        # YOUR CODE HERE
        return sum(self.votes.values())
    def winner(self):
        """Returns the list of winners of the election."""
        # YOUR CODE HERE
        if self.total_votes() == 0:
          winners = None
        else:
          winners = set()
          all_values = self.votes.values()
          max_value = max(all_values)
          for a in self.votes.keys():
            if self.votes.get(a) == max_value:
              winners.add(a)
        return winners
    def margin(self):
        """Returns the margin of victory of the winner."""
        # YOUR CODE HERE
        if self.total_votes() == 0:
          return None
        elif len(self.winner()) > 1:
          return 0
        else:
          winner_votes = max(list(self.votes.values()))
          sec_winner = 0
          for a in self.votes.values():
            if a > sec_winner and a < winner_votes:
              sec_winner = a
          return winner_votes - sec_winner

# You can use this cell to test your code. 

# YOUR CODE HERE
e = Election()
assert e.margin() == None

e.vote('a')
e.vote('b')
e.vote('a')
e.vote('c')
e.vote('b')
print('Margin: ', e.margin())

### For this question, you received 5 out of 5 points.

# 5 points: Tests for total_votes method. 

e = Election()
assert e.total_votes() == 0

e.vote('a')
e.vote('b')
e.vote('a')
assert e.total_votes() == 3

e.vote('c')
e.vote('b')
assert e.total_votes(), 5

### BEGIN HIDDEN TESTS
f = Election()
f.vote(1)
for _ in range(3):
    f.vote(2)
assert f.total_votes() == 4
for i in range(10):
    f.vote(i)
assert f.total_votes() == 14
### END HIDDEN TESTS

### For this question, you received 5 out of 5 points.

# 5 points: Tests for winner method.

e = Election()
assert e.winner() == None

e.vote('a')
e.vote('b')
e.vote('a')
assert e.winner() == {'a'}

e.vote('c')
e.vote('b')
assert e.winner() == {'a', 'b'}

### BEGIN HIDDEN TESTS
f = Election()
for j in range(4):
    for i in range(10):
        f.vote(i)
assert f.winner() == set(range(10))
f.vote(4)
assert f.winner() == {4}
### END HIDDEN TESTS

### For this question, you received 5 out of 5 points.

# 5 points: Tests for margin method.

e = Election()
assert e.margin() == None

e.vote('a')
e.vote('b')
e.vote('a')
assert e.margin() == 1

e.vote('c')
e.vote('b')
assert e.margin() == 0

### BEGIN HIDDEN TESTS
f = Election()
for j in range(4):
    for i in range(10):
        f.vote(i)
assert f.margin() == 0
f.vote(4)
assert f.margin() == 1
f.vote(4)
assert f.margin() == 2
### END HIDDEN TESTS

